[workspace]
authors = ["ssunsonic <erictsun02@gmail.com>"]
channels = ["conda-forge"]
description = "Bat counting with YOLOv11 and SORT optimized for edge deployment"
name = "2025_lagattuta_bats"
platforms = ["linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.12"
ffmpeg = "*"
numpy = ">=1.26,<2"
scipy = ">=1.11,<2"
pandas = ">=2.2.3,<3"
scikit-image = ">=0.25.1,<0.26"
matplotlib = ">=3.8,<4"

[pypi-dependencies]
ultralytics = ">=8.3.62,<9"
filterpy = ">=1.4.5,<2"
lap = "*"
opencv-python = "==4.10.0.84"